---
title: "Lab 5"
author: "Samuel Kelly"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Task 1
Get working directory
```{r}
getwd()
```

# Task 2

## mybin Function
```{r}
mybin=function(iter=100,n=10, p=0.5){
# make a matrix to hold the samples
#initially filled with NA's
sam.mat=matrix(NA,nr=n,nc=iter, byrow=TRUE)
#Make a vector to hold the number of successes in each trial
succ=c()
for( i in 1:iter){
#Fill each column with a new sample
sam.mat[,i]=sample(c(1,0),n,replace=TRUE, prob=c(p,1-p))
#Calculate a statistic from the sample (this case it is the sum)
succ[i]=sum(sam.mat[,i])
}
#Make a table of successes
succ.tab=table(factor(succ,levels=0:n))
#Make a barplot of the proportions
barplot(succ.tab/(iter), col=rainbow(n+1), main="Binomial simulation", xlab="Number of successes")
succ.tab/iter
}
```

## Iterations
```{r}
mybin(n = 10,p = .7,iter = 100)
mybin(n = 10,p = .7,iter = 200)
mybin(n = 10,p = .7,iter = 500)
mybin(n = 10,p = .7,iter = 1000)
obj = mybin(n = 10,p = .7,iter = 10000)
```

## Table
```{r}
obj
dbin<-round(dbinom(x = 0:10,prob = .7,size = 10),4)
names(dbin)=0:10
dbin
```

# Task 3

## Marbles
There is a bag of 20 marbles, 12 white(1) and 8 black(0).

## Sample of marbles

```{r}
sample(c(1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0),size=5,prob=NULL, replace=F)

sample(c(1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0),size=5,prob=NULL, replace=T)
```

## Hypergeometric Function

```{r}
myhyper=function(iter=100,N=20,r=12,n=5){
# make a matrix to hold the samples
#initially filled with NA's
sam.mat=matrix(NA,nr=n,nc=iter, byrow=TRUE)
#Make a vector to hold the number of successes over the trials
succ=c()
for( i in 1:iter){
#Fill each column with a new sample
sam.mat[,i]=sample(rep(c(1,0),c(r,N-r)),n,replace=FALSE)
#Calculate a statistic from the sample (this case it is the sum)
succ[i]=sum(sam.mat[,i])
}
#Make a table of successes
succ.tab=table(factor(succ,levels=0:n))
#Make a barplot of the proportions
barplot(succ.tab/(iter), col=rainbow(n+1), main="HYPERGEOMETRIC simulation", xlab="Number of successes")
succ.tab/iter
}
```

## Iterations

```{r}
myhyper(iter = 100,n = 5,N = 20,r = 12)
myhyper(iter = 200,n = 5,N = 20,r = 12)
myhyper(iter = 500,n = 5,N = 20,r = 12)
myhyper(iter = 1000,n = 5,N = 20,r = 12)
myhyper(iter = 10000,n = 5,N = 20,r = 12)
```

