---
title: "Lab 2"
author: "Samuel Kelly"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Tasks

## Task 1
Working Directory
```{r}
getwd()
```

## Task 2
Display head of EPAGAS.csv file
```{r}
mpg.df<-read.csv("EPAGAS.csv")
head(mpg.df)
```

## Task 3
  a. Transform the mpg variable to z and verify these results, $$z=0, s=1$$
```{r}
mpg<-mpg.df$MPG
z=(mpg-mean(mpg))/sd(mpg)
layout(matrix(c(1, 2, 3), nrow = 1, ncol = 3))
head(z)
print(paste0("mean = ",round(mean(z), digits = 4)), quote = FALSE)
print(paste0("sd = ",sd(z)),quote=F)
```

  b. Find possible outliers of z.
```{r}
z[abs(z)>3]
mpg[abs(z)>3]
z[abs(z)>=2 & abs(z)<=3]
```
  c. Find actual outliers
```{r}
mpg[abs(z)>3]
```
  
  d. Use lattice package to create dotplot
```{r}
library(lattice)
mpg.col = ifelse(abs(z)>3, "Red",
                 ifelse(abs(z)>=2 & abs(z)<=3, "Blue", "Black"))
dp<-dotplot(mpg,col=mpg.col)
dp
```
  
## Task 4
  
  a. Boxplot of mpg variable
```{r}
bpMPG<- boxplot(mpg.df$MPG, col = "Green", 
                notch = T, main = "Boxplot of MPG", 
                horizontal = T, xlab ="MPG")
```
 
  b. 
