---
title: "Lab 7"
author: "Samuel Kelly"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: yes
    theme: spacelab
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Task 1

## Working Directory

```{r}
getwd()
```

# Task 2

## mychisim Function

```{r}
mychisim<-function(n1=10,sigma1=3,mean1=5,iter=1000,ymax=0.1,x=20, y=0.1){    # adjust ymax to make graph fit
y1=rnorm(n1*iter,mean=mean1,sd=sigma1)# generate iter samples of size n1
#n1*iter is the size of the matrix where each iter column is a new sample of the population
data1.mat=matrix(y1,nrow=n1,ncol=iter,byrow=TRUE) # Each column is a sample size n1

ssq1=apply(data1.mat,2,var) # ssq1 is s squared

w=(n1-1)*ssq1/sigma1^2      #chi-sq stat

hist(w,freq=FALSE, ylim=c(0,ymax), # Histogram with annotation
main=substitute(paste("Sample size = ",n[1]," = ",n1," statistic = ",chi^2)),
xlab=expression(paste(chi^2, "Statistic",sep=" ")), las=1)
lines(density(w),col="Blue",lwd=3) # add a density plot
curve(dchisq(x,n1-1),add=TRUE,col="Red",lty=2,lwd=3) # add a theoretical curve
title=expression(chi^2==frac((n[1]-1)*s^2,sigma^2)) #mathematical annotation -see ?plotmath
legend(x,y,c("Simulated","Theoretical"),col=c("Blue","Red"),lwd=4,lty=1:2,bty="n",title=title) # Legend #
invisible(list(w=w,summary=summary(w),sd=sd(w),fun="Chi-sq")) # some output to use if needed
}
```

## 4 Chisq plots

```{r}
mychisim(n1 = 10,iter = 1000,mean1 = 10,sigma1 = 4,x = 20,y = .06,ymax = .11)
mychisim(n1 = 20,iter = 1000,mean1 = 10,sigma1 = 4,x = 30,y = .04,ymax = .07)
mychisim(n1 = 100,iter = 1000,mean1 = 10,sigma1 = 4,ymax = .03,x = 130,y = .020)
mychisim(n1 = 200,iter = 1000,mean1 = 10,sigma1 = 4,ymax = .02,x = 240,y = .015)
```

## Histogram of w

```{r}
chisq = mychisim(n1 = 10,iter = 1500,mean1 = 20,sigma1 = 10,ymax = .11,x = 20,y = .08)
hist(chisq$w,main = "Histogram of Chisq",col = rainbow(15),xlab = expression(paste(chi^2," Value")))
```

# Task 3

## myTsim function

```{r}
myTsim<-function(n1=10,sigma1=3,mean1=5,iter=1000,ymax=0.1,x=2,y=0.3,...){    # adjust ymax to make graph fit
y1=rnorm(n1*iter,mean=mean1,sd=sigma1)# generate iter samples of size n1

data1.mat=matrix(y1,nrow=n1,ncol=iter,byrow=TRUE) # Each column is a sample size n1

sd1=apply(data1.mat,2,sd) # sd
ybar=apply(data1.mat,2,mean)  # mean

w=(ybar-mean1)/(sd1/sqrt(n1))      #T stat

hist(w,freq=FALSE, ylim=c(0,ymax), # Histogram with annotation
main=substitute(paste("Sample size = ",n[1]," = ",n1," statistic = ",T," iterations= ",iter)),
xlab=expression(paste(T, "Statistic",sep=" ")), las=1)
lines(density(w),col="Blue",lwd=3) # add a density plot
curve(dt(x,n1-1),add=TRUE,col="Red",lty=2,lwd=3) # add a theoretical curve
title=expression(T==frac((bar(y)-mu),s/sqrt(n1))) #mathematical annotation -see ?plotmath
legend(x,y,c("Simulated","Theoretical"),col=c("Blue","Red"),lwd=4,lty=1:2,bty="n",title=title) # Legend #
invisible(list(w=w,summary=summary(w),sd=sd(w),fun="T")) # some output to use if needed
}
```

## 4 plots

```{r}
myTsim(n1 = 10,iter = 1000,mean1 = 10,sigma1 = 4,ymax = .4)
myTsim(n1 = 20,iter = 1000,mean1 = 10,sigma1 = 4,ymax = .4)
myTsim(n1 = 100,iter = 1000,mean1 = 10,sigma1 = 4,ymax = .4,x = -3.5)
myTsim(n1 = 200,iter = 1000,mean1 = 10,sigma1 = 4,ymax = .4)
```

## Histogram of w

```{r}
T <- myTsim(n1 = 10,iter = 1500,mean1 = 20,sigma1 = 10,ymax = .4)
hist(T$w,xlab = "T Value",col = rainbow(15))
```

############################################################# RECORD

# Task 4


